name = "adventskalender"
main = "pia-und-paul-github/worker/index.ts"
compatibility_date = "2026-10-03"

[[d1_databases]]
binding = "DB"
database_name = "pia-und-paul-adventskalender"
database_id = "39d1992c-80b6-48d9-bb74-8ed05da125d7"
migrations_dir = "pia-und-paul-github/migrations"
